config/routes.rb
Rails.application.routes.draw do
  resources :areas
  resources :companies do
    resources :employees, only: [:create, :destroy]
  end

  root to: 'companies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :employees
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :employees, dependent: :delete_all
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company
  belongs_to :area
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name)
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @employee = Employee.new
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to @company, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def create
    @employee = Employee.new(employee_params)
    @employee.company = Company.find(params[:company_id])
    @employee.save
    redirect_to @employee.company
  end

  def destroy
    @employee = Product.find(params[:id])
    @company = @employee.company
    @employee.destroy
    redirect_to @company #, alert: 'empleado eliminado'
  end

  private
  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :area_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/areas/_form.html.erb
<%= form_with(model: area, local: true) do |form| %>
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Nombre" %>
    <%= form.text_field :name, id: :area_name %>
  </div>

  <div class="actions">
    <%= form.submit "Listo", class:'btn btn-dark' %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<div class="row">
  <div class="col-4">

  </div>
  <div class="col-5">
    <div class="card index">
      <h1 class="text-center">Editar area</h1>
      <hr>
      <div class="container">
        <%= render 'form', area: @area %>
        <hr>
        <hd><%= link_to 'Ver area', @area, class:'btn btn-dark' %>
        <hd><%= link_to 'Salir', areas_path, class:'btn btn-dark' %>
      </div>

    </div>
  </div>
</div>

app/views/areas/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-4">

  </div>
  <div class="col-5">
    <div class="card index">
      <h1 class="text-center">Areas</h1>
      <hr>
      <div class="container">
        <table>
          <thead>
            <tr>
              <th>Nombre</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @areas.each do |area| %>
              <tr>
                <td class="pr-5"><%= area.name %></td>
                <td><%= link_to 'Ver', area, class:'btn btn-dark ml-5' %></td>
                <td><%= link_to 'Editar', edit_area_path(area), class:'btn btn-dark ml-2' %></td>
                <td><%= link_to 'Eliminar', area, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-dark ml-2' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>
        <hr>
      </div>
      <hd><%= link_to 'Nueva area', new_area_path, class:'btn btn-dark ml-3' %>
    </div>
  </div>
</div>

app/views/areas/new.html.erb
<div class="row">
  <div class="col-4">

  </div>
  <div class="col-5">
    <div class="card index">
      <h1 class="text-center">Nueva Area</h1>
      <hr>
      <div class="container">
          <%= render 'form', area: @area %>
      </div>
      <hr>
      <div class="container">
        <hd><%= link_to 'Salir', areas_path, class:'btn btn-dark' %>
      </div>
    </div>
  </div>
</div>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-4">

  </div>
  <div class="col-5">
    <div class="card index">
      <h1 class="text-center">Nombre de area:</h1>
      <div class="container">
        <h1><%= @area.name %></h1>

        <hd><%= link_to 'Editar area', edit_area_path(@area), class:'btn btn-dark' %>
        <hd><%= link_to 'Salir', areas_path, class:'btn btn-dark' %>
      </div>
    </div>
  </div>
</div>

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Nombre" %>
    <%= form.text_field :name, id: :company_name %>
  </div>

  <div class="actions">
    <%= form.submit "Listo", class:'btn btn-dark' %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div class="row">
  <div class="col-4">

  </div>
  <div class="col-5">
    <div class="card index">

      <h1 class="text-center">Editar compañia</h1>
      <div class="container">
        <hr>
        <%= render 'form', company: @company %>
        <hr>
        <%= link_to 'Ver compañia', @company, class:'btn btn-dark' %>

        <%= link_to 'Salir', companies_path, class:'btn btn-dark' %>
      </div>


    </div>
  </div>
</div>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-4">

  </div>
  <div class="col-5">
    <div class="card index">
      <h1 class="text-center">Compañias</h1>

      <table class="ml-3">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Cantidad</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <hr>
          <tbody>
              <% @companies.each do |company| %>
              <tr>
                <td><%= link_to company.name, company %></td>
                <td><%= company.employees.count %></td>
                <td><%= link_to 'Editar', edit_company_path(company), class:'btn btn-dark' %></td>
                <td><%= link_to 'Eliminar', company, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-dark' %></td>
              </tr>
              <% end %>
          </tbody>
      </table>
      <hr>
      <br>
      <div class="container">
        <hd class="abajo"><%= link_to 'Nueva Empresa', new_company_path, class:'btn btn-dark' %>
      </div>
  </div>
</div>

app/views/companies/new.html.erb
<div class="row">
  <div class="col-4">

  </div>
  <div class="col-5">
    <div class="card index">
      <h1 class="text-center">Nueva compañia</h1>
      <div class="container">
        <hr>
        <%= render 'form', company: @company %>
        <hr>
        <%= link_to 'Salir', companies_path, class:'btn btn-dark' %>
      </div>
    </div>
  </div>
</div>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-4">

  </div>
  <div class="col-5">
    <div class="card index">
      <h1 class="text-center">Nombre compañia: <%= @company.name %></h1>
      <hr>
      <div class="container">
        <h1>Ingreso de empleado</h1>

        <%= form_with(model: [ @company, @employee ]) do |form| %>
          <%= form.label :first_name, "Nombre:" %>
          <%= form.text_field :first_name %>
          <br>
          <%= form.label :last_name, "Apellido:" %>
          <%= form.text_field :last_name %>
          <br>
          <%= form.label :email, "Email:" %>
          <%= form.text_field :email %>
          <br>
          <%= form.label :area_id, "Area:" %>
          <%= form.select :area_id, Area.pluck(:name, :id) %>
          <br>
          <%= form.submit "Crear", class:'btn btn-dark' %>
        <% end %>
      </div>


      <div class="card p-3">

          <table>
            <thead>
              <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Email</th>
                <th>Area</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @company.employees.each do |e| %>
                <tr>
                  <td><%= e.first_name %></td>
                  <td><%= e.last_name %></td>
                  <td><%= e.email %></td>
                  <td><%= e.area.name %></td>
                  <td><%= link_to "Eliminar", company_employees_path(@company, e), method: :delete, data: { :confirm => "¿Desea Eliminar?"}, :class => "btn btn-dark" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="container">
          <hd><%= link_to 'Editar compañia', edit_company_path(@company), class:'btn btn-dark' %>
          <hd><%= link_to 'Salir', companies_path, class:'btn btn-dark' %>
        </div>

    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active">
        <i class="fas fa-home pt-2"></i>
      </li>

      <li class="nav-item active">
        <%= link_to "Home", root_path, class:'nav-link'%>
      </li>

      <li class="nav-item">
        <%= link_to "Nueva compañia", new_company_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to "Nueva area", new_area_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudConAsociacion</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Courgette&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"></script>
  </body>
</html>